/**
 * Champions-legal held items (generated by data/scripts/fetch-champions-items.mjs
 * from Showdown base + champions mod + PokéAPI Korean names). Loaded once and
 * cached. `name` is the Showdown display name used by the damage engine; `ko`
 * is shown to the user.
 */
export type ItemCat = 'mega' | 'berry' | 'plate' | 'gem' | 'item'
export interface ItemEntry {
  id: string
  name: string
  ko: string
  cat: ItemCat
}

let cache: Promise<ItemEntry[]> | null = null

export function loadItems(): Promise<ItemEntry[]> {
  cache ??= fetch('/data/items.json')
    .then((res) => (res.ok ? (res.json() as Promise<ItemEntry[]>) : []))
    .catch(() => [])
  return cache
}

/** Category order + labels for grouping the item picker. */
export const ITEM_CAT_ORDER: ItemCat[] = ['item', 'berry', 'plate', 'gem', 'mega']
export const ITEM_CAT_LABEL: Record<ItemCat, { ko: string; en: string }> = {
  item: { ko: '일반', en: 'Items' },
  berry: { ko: '나무열매', en: 'Berries' },
  plate: { ko: '플레이트', en: 'Plates' },
  gem: { ko: '젬', en: 'Gems' },
  mega: { ko: '메가스톤', en: 'Mega Stones' },
}

/** Groups items by category in display order. */
export function groupItems(items: ItemEntry[]): { cat: ItemCat; items: ItemEntry[] }[] {
  return ITEM_CAT_ORDER.map((cat) => ({ cat, items: items.filter((i) => i.cat === cat) })).filter(
    (g) => g.items.length > 0,
  )
}
